import test from 'node:test';import assert from 'node:assert/strict';
import {validateDesignSpec,designHash,verifyDesign} from '../server/studio-contract.mjs';
import {validateRepair,unresolvedRepairFailures} from '../server/studio-repair.mjs';
const make=()=>({schemaVersion:1,title:'Pin and bore tool fixture',description:'A test not a product',units:'mm',requirements:[{id:'R1',text:'Insert a post'}],assumptions:[],unknowns:[],questions:[],parts:[{id:'base',name:'Base',kind:'printed',material:'PLA',color:'#123456',shape:{type:'box',size:[30,30,10]},position:[0,0,5],rotation:[0,0,0],holes:[{axis:'z',diameter:10.4,position:[0,0,0]}]},{id:'post',name:'Post',kind:'printed',material:'PLA',color:'#123456',shape:{type:'cylinder',radius:5,height:30},position:[0,0,20],rotation:[0,0,0]}],assembly:[{id:'fit',title:'Fit',partIds:['base','post'],requires:[],instructions:['Check'],checks:['Check']}],verificationRequests:[{id:'engage',requirementId:'R1',type:'shaftHole',shaftPartId:'post',holePartId:'base',holeIndex:0,minimumEngagementMm:5,diametralClearanceMm:[.2,.5]}]});
test('tool intent is bound to design hash and does not award PASS before host execution',()=>{const s=make(),before=JSON.stringify(s),clean=validateDesignSpec(s);assert.equal(JSON.stringify(s),before);assert.deepEqual(clean.verificationRequests,s.verificationRequests);assert.equal(verifyDesign(s).overall,'UNVERIFIED');const old=designHash(s);s.verificationRequests[0].minimumEngagementMm=6;assert.notEqual(designHash(s),old);});
test('strict request identity, geometry references, bounds and unknown fields',()=>{for(const edit of [s=>s.verificationRequests[0].requirementId='missing',s=>s.verificationRequests[0].holePartId='post',s=>s.verificationRequests[0].holeIndex=9,s=>s.verificationRequests[0].minimumEngagementMm=0,s=>s.verificationRequests[0].diametralClearanceMm=[1,0],s=>s.verificationRequests[0].code='run()',s=>s.verificationRequests.push(s.verificationRequests[0])]){const s=make();edit(s);assert.throws(()=>validateDesignSpec(s));}});
test('envelope and motion samples are bounded and reference existing parts',()=>{const s=make();s.verificationRequests=[{id:'size',requirementId:'R1',type:'envelope',partIds:['base','post'],maxSizeMm:[100,100,100]},{id:'rotate',requirementId:'R1',type:'rotationSweep',partIds:['post'],axis:'y',originMm:[0,0,20],minDeg:-15,maxDeg:15}];assert.doesNotThrow(()=>validateDesignSpec(s));s.verificationRequests[1].partIds.push('post');assert.throws(()=>validateDesignSpec(s));});
test('repair cannot erase or weaken its requested test; only changing the design is accepted',()=>{const s=make(),weak=make();weak.verificationRequests[0].minimumEngagementMm=1;assert.throws(()=>validateRepair(s,weak),/verification request/);const omitted=make();delete omitted.verificationRequests;assert.throws(()=>validateRepair(s,omitted),/verification request/);const moved=make();moved.parts[1].position[2]--;assert.doesNotThrow(()=>validateRepair(s,moved));assert.deepEqual(unresolvedRepairFailures([{id:'build-execution',status:'FAIL',critical:true}],{claims:[{id:'build-execution',status:'PASS',critical:true}]}),[]);});
test('model repair feedback identifies the exact invalid tool field, not a misleading array index',()=>{
  for(const [edit,path] of [
    [r=>r.diametralClearanceMm=[-.2,.4],'diametralClearanceMm[0]'],
    [r=>r.minimumEngagementMm=0,'minimumEngagementMm'],
    [r=>r.holeIndex=24,'holeIndex'],
    [r=>r.shaftPartId='missing','shaftPartId'],
  ]){const s=make();edit(s.verificationRequests[0]);assert.throws(()=>validateDesignSpec(s),e=>e.message.startsWith('verificationRequests[0].'+path+':'));}
  const s=make();s.verificationRequests=[{id:'sweep',requirementId:'R1',type:'rotationSweep',partIds:['post'],axis:'z',originMm:[0,0,NaN],minDeg:-15,maxDeg:15}];
  assert.throws(()=>validateDesignSpec(s),e=>e.message.startsWith('verificationRequests[0].originMm[2]:'));
});
