import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {loadSourceLibrary} from '../server/studio-library.mjs';
const hash='a'.repeat(64),schema='m4ke-model-library-candidate-index-2';
const record=(extra={})=>({name:'Raspberry Pi fixture',sku:'1234',sha256:hash,bytes:42,hardware_revision:'UNVERIFIED',local_file:'/fixture-private/secret.step',relative_file:'secret/file.step',source_path:'supplier/source.step',source_url:'https://example.com/source.step',product_url:'https://example.com/part',native_check:{status:'NATIVE_IMPORT_VALID',native_valid:true,sha256:hash,solids:2,size_mm:[40,30,5]},...extra});
async function fixture(){const root=await mkdtemp(path.join(tmpdir(),'m4ke-source-library-')),folder=path.join(root,'database','model-library');await mkdir(folder,{recursive:true});return {root,folder,put:(name,records=[record()],extra={})=>writeFile(path.join(folder,name),JSON.stringify({schema,records,...extra})),close:()=>rm(root,{recursive:true,force:true})};}
test('source library chooses numeric latest index and recomputes supplier-intake counts',async()=>{const f=await fixture();try{await f.put('CANDIDATE-INDEX-20260927-2.json',[record({name:'Old'})]);await f.put('CANDIDATE-INDEX-20260927-10.json',[record(),record({sha256:'b'.repeat(64),native_check:{status:'NATIVE_IMPORT_REQUIRES_REVIEW',native_valid:false,sha256:'b'.repeat(64)}}),record({sha256:'c'.repeat(64),native_check:{status:'PENDING_LARGE_SOURCE_REVIEW'}})],{summary:{source_entries:99999,physically_verified:99999}});const result=await loadSourceLibrary(f.root);assert.equal(result.indexFile,'CANDIDATE-INDEX-20260927-10.json');assert.deepEqual(result.summary,{candidateCount:3,uniqueSourceFiles:3,nativeReportedValid:1,nativeReviewRequired:1,nativePending:1});assert(result.records.every(r=>r.buildQualified===false&&r.physicalValidation==='UNKNOWN'));assert.match(result.indexSha256,/^[a-f0-9]{64}$/);}finally{await f.close();}});
test('source library strips local paths, credentials and unsafe URL schemes',async()=>{const f=await fixture();try{await f.put('CANDIDATE-INDEX-20260927-01.json',[record({name:'Safe\u0000 name',source_url:'https://user:password@example.com/model',product_url:'javascript:alert(1)'})]);const result=await loadSourceLibrary(f.root),r=result.records[0];assert.equal(r.sourceUrl,null);assert.equal(r.productUrl,null);assert.equal(r.name,'Safe  name');assert.equal(JSON.stringify(result).includes('/fixture-private'),false);for(const key of ['source_path','local_file','relative_file'])assert.equal(Object.hasOwn(r,key),false);}finally{await f.close();}});
test('native reported validity requires matching recorded hashes and nested status, not the stale top-level label',async()=>{const f=await fixture();try{await f.put('CANDIDATE-INDEX-20260927-01.json',[record({native_validation:'PENDING'}),record({native_check:{status:'NATIVE_IMPORT_VALID',native_valid:true,sha256:'b'.repeat(64)}}),record({native_validation:'PASS',native_check:null})]);const result=await loadSourceLibrary(f.root);assert.deepEqual(result.records.map(r=>r.nativeCheck.status),['NATIVE_IMPORT_REPORTED_VALID','REVIEW_REQUIRED','PENDING']);}finally{await f.close();}});
test('native validity does not erase source-specific fit blockers or discontinuation findings',async()=>{const f=await fixture();try{await f.put('CANDIDATE-INDEX-20260927-05.json',[record({sku:'2011',eligibility:'blocked_for_fit_nominal_dimension_mismatch',source_review:[{finding:'CAD 60 x 37 x 7.5 mm differs from nominal 60 x 36 x 7 mm.',source:'https://www.adafruit.com/product/2011',catalog_eligibility:'revision_and_fit_review',local_file:'/private/never-export'}]}),record({sku:'6049',source_review:[{finding:'This exact SKU is discontinued; do not substitute another model.',source:'https://www.adafruit.com/product/6049'}]})]);const result=await loadSourceLibrary(f.root);assert.equal(result.records[0].nativeCheck.status,'NATIVE_IMPORT_REPORTED_VALID');assert.equal(result.records[0].eligibility,'blocked_for_fit_nominal_dimension_mismatch');assert.match(result.records[0].qualificationNotes[0].finding,/differs from nominal/);assert.match(result.records[1].qualificationNotes[0].finding,/discontinued/);assert.equal(JSON.stringify(result).includes('never-export'),false);assert(result.records.every(r=>r.buildQualified===false));}finally{await f.close();}});
test('invalid latest schema cannot silently resurrect an older good catalog',async()=>{const f=await fixture();try{await f.put('CANDIDATE-INDEX-20260927-01.json');await f.put('CANDIDATE-INDEX-20260927-02.json',[],{schema:'unreviewed-format'});const result=await loadSourceLibrary(f.root);assert.equal(result.available,false);assert.equal(result.status,'INVALID_INDEX');assert.deepEqual(result.records,[]);}finally{await f.close();}});
test('missing index is a nonfatal unavailable state and unrelated filenames are ignored',async()=>{const f=await fixture();try{await f.put('manifest.json');await f.put('CANDIDATE-INDEX-latest.json');const result=await loadSourceLibrary(f.root);assert.equal(result.status,'NOT_IMPORTED');assert.equal(result.available,false);}finally{await f.close();}});
test('oversized files and excessive records are refused without altering teammate files',async()=>{const f=await fixture();try{const name='CANDIDATE-INDEX-20260927-01.json';await f.put(name,Array.from({length:2001},()=>record()));assert.equal((await loadSourceLibrary(f.root)).status,'INVALID_INDEX');const before=Buffer.alloc(8*1024*1024+1,32);await writeFile(path.join(f.folder,name),before);assert.equal((await loadSourceLibrary(f.root)).status,'INVALID_INDEX');assert.deepEqual(await readFile(path.join(f.folder,name)),before);}finally{await f.close();}});
test('index symlinks are not followed into other files',async t=>{const f=await fixture();try{await f.put('source.json');try{await symlink(path.join(f.folder,'source.json'),path.join(f.folder,'CANDIDATE-INDEX-20260927-01.json'),'file');}catch(e){if(['EPERM','EACCES'].includes(e.code)){t.skip('Symlink creation requires unavailable host privileges');return;}throw e;}assert.equal((await loadSourceLibrary(f.root)).status,'INVALID_INDEX');}finally{await f.close();}});
