import test from 'node:test';
import assert from 'node:assert/strict';
import {applyVerificationPlan,planDesignVerification} from '../server/studio-verification-plan.mjs';
const spec=()=>({schemaVersion:1,title:'Tool-plan fixture',description:'Synthetic test, not a toy design',units:'mm',requirements:[{id:'R1',text:'Stay within 50 mm'}],assumptions:[],unknowns:[],questions:[],parts:[{id:'p',name:'Part',kind:'printed',material:'PLA',color:'#123456',shape:{type:'box',size:[20,20,4]},position:[0,0,0],rotation:[0,0,0]}],assembly:[{id:'a',title:'Inspect',partIds:['p'],requires:[],instructions:['Inspect'],checks:['Measure']}]});
const request={id:'envelope',requirementId:'R1',type:'envelope',partIds:['p'],maxSizeMm:[50,50,50]};
test('tool planner adds validated host requests without changing any design geometry',()=>{const s=spec();const result=applyVerificationPlan(s,{checks:[request],uncovered:[]});assert.deepEqual(result.spec.parts,s.parts);assert.deepEqual(result.addedCheckIds,['envelope']);});
test('tool planner cannot weaken an existing test or introduce result claims',()=>{const s={...spec(),verificationRequests:[request]};assert.throws(()=>applyVerificationPlan(s,{checks:[{...request,maxSizeMm:[100,100,100]}],uncovered:[]}),/cannot alter/);assert.throws(()=>applyVerificationPlan(s,{checks:[],uncovered:[],status:'PASS'}),/only/);});
test('unknown parts and requirements are rejected',()=>{assert.throws(()=>applyVerificationPlan(spec(),{checks:[{...request,partIds:['missing']}],uncovered:[]}));assert.throws(()=>applyVerificationPlan(spec(),{checks:[],uncovered:[{requirementId:'missing',reason:'x'}]}));});
test('actual model response selects tools; transport failure preserves candidate with unavailable status',async()=>{const args={spec:spec(),skills:{plan:'Select tools',hashes:{plan:'fixture'}},model:'fixture',endpoint:'http://127.0.0.1:11434'};const result=await planDesignVerification({...args,infer:async()=>({message:{content:JSON.stringify({checks:[request],uncovered:[]})}})});assert.equal(result.record.status,'SELECTED');assert.equal(result.record.doesNotSupplyEvidence,true);const failure=await planDesignVerification({...args,infer:async()=>{throw Error('offline');}});assert.equal(failure.record.status,'UNAVAILABLE');assert.deepEqual(failure.spec.parts,args.spec.parts);});
