import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {loadCatalog,snapshotKernel,generationCatalogIssues} from '../server/studio-catalog.mjs';
async function fixture(){const root=await mkdtemp(path.join(tmpdir(),'m4ke-catalog-test-'));await mkdir(path.join(root,'cad'));await mkdir(path.join(root,'catalog','models'),{recursive:true});for(const n of ['worker.py','requirements.txt','catalog_geometry.py'])await writeFile(path.join(root,'cad',n),'fixture '+n);const bytes=Buffer.from('Fixture bytes are not actual STEP; tests snapshot hashes, not CAD validity.'),sha=createHash('sha256').update(bytes).digest('hex');await writeFile(path.join(root,'catalog','models','fixture.step'),bytes);const manifest={schemaVersion:1,components:[{id:'source-part',geometry:{step:'models/fixture.step',sha256:sha,units:'mm'}}],materials:[],kits:[]};await writeFile(path.join(root,'catalog','manifest.json'),JSON.stringify(manifest));return {root,manifest,sha,bytes,close:()=>rm(root,{recursive:true,force:true})};}
test('freezes hash-checked source bytes and kernel code into self-contained job catalog',async()=>{const f=await fixture();try{const dir=path.join(f.root,'job'),result=await snapshotKernel(f.root,dir,{parts:[{shape:{type:'catalog',catalogId:'source-part'}}]});assert(result.files.includes('kernel/worker.py'));assert(result.files.includes('catalog/models/'+f.sha+'.step'));const frozen=JSON.parse(await readFile(path.join(dir,'catalog','manifest.json'),'utf8'));assert.equal(frozen.components[0].geometry.step,'models/'+f.sha+'.step');assert.equal(frozen.components[0].geometry.originalPath,'models/fixture.step');assert.equal(frozen.parentManifestSha256,(await loadCatalog(f.root)).manifestSha256);await writeFile(path.join(f.root,'cad','worker.py'),'later revision');assert.equal(await readFile(path.join(dir,'kernel','worker.py'),'utf8'),'fixture worker.py');}finally{await f.close();}});
test('corrupt source cannot be snapshot as verified dependency',async()=>{const f=await fixture();try{await writeFile(path.join(f.root,'catalog','models','fixture.step'),'corrupt');await assert.rejects(snapshotKernel(f.root,path.join(f.root,'job'),{parts:[{shape:{type:'catalog',catalogId:'source-part'}}]}),/hash mismatch/);}finally{await f.close();}});
test('catalog ID and path fail closed; no arbitrary network fetch occurs',async()=>{const f=await fixture();try{await assert.rejects(snapshotKernel(f.root,path.join(f.root,'job'),{parts:[{shape:{type:'catalog',catalogId:'unknown'}}]}),/no source STEP/);f.manifest.components[0].geometry.step='../../secret.step';await writeFile(path.join(f.root,'catalog','manifest.json'),JSON.stringify(f.manifest));await assert.rejects(snapshotKernel(f.root,path.join(f.root,'job2'),{parts:[{shape:{type:'catalog',catalogId:'source-part'}}]}),/Unsafe/);}finally{await f.close();}});

const sourceGeometry={step:'models/synthetic.step',sha256:'a'.repeat(64)};
const rating=(value,unit)=>({value,unit,basis:'MANUFACTURER_PUBLISHED'});
const motorCatalog={components:[{id:'motor-1098',sku:'1098',geometry:sourceGeometry,ratings:{noLoadRpm:rating(270,'rpm'),theoreticalStallTorqueKgfCm:rating(.44,'kgf*cm'),theoreticalStallCurrentA:rating(.36,'A'),voltageV:rating(6,'V')}},{id:'motor-992',sku:'992',geometry:sourceGeometry,ratings:{noLoadRpm:rating(130,'rpm'),theoreticalStallTorqueKgfCm:rating(.74,'kgf*cm'),theoreticalStallCurrentA:rating(.36,'A'),voltageV:rating(6,'V')}}]};
const input=(value,basis='MANUFACTURER')=>({value,basis,source:'test fixture provenance'});
const motorDraft=()=>({parts:[{id:'left',shape:{type:'catalog',catalogId:'motor-1098'}},{id:'right',shape:{type:'catalog',catalogId:'motor-1098'}}],physicsInputs:{motorNoLoadRpm:input(270),motorStallTorqueNm:input(.04315),motorStallA:input(.36),motorVoltage:input(6),motorTorqueNm:input(.01,'ASSUMED')}});
test('generation catalog guard accepts duplicate selected SKU and rounded Nm conversion without mutation',()=>{const spec=motorDraft(),before=structuredClone(spec),catalog=structuredClone(motorCatalog);assert.deepEqual(generationCatalogIssues(spec,catalog),[]);assert.deepEqual(spec,before);assert.deepEqual(catalog,motorCatalog);});
test('generation catalog guard rejects ratings borrowed from another motor before freeze',()=>{const spec=motorDraft();Object.assign(spec.physicsInputs,{motorNoLoadRpm:input(130),motorStallTorqueNm:input(.07257),motorStallA:input(.7),motorVoltage:input(12)});const issues=generationCatalogIssues(spec,motorCatalog);assert.equal(issues.length,4);for(const key of ['motorNoLoadRpm','motorStallTorqueNm','motorStallA','motorVoltage'])assert(issues.some(i=>i.includes(key)&&i.includes('motor-1098')));});
test('generation catalog guard never guesses scalar ratings across mixed selected motor SKUs',()=>{const spec=motorDraft();spec.parts[1].shape.catalogId='motor-992';assert.match(generationCatalogIssues(spec,motorCatalog).join('\n'),/Mixed motor ratings are unsupported/);});
test('generation catalog guard rejects usable torque at stall regardless of basis or inflated declared stall',()=>{for(const basis of ['ASSUMED','USER','MANUFACTURER','MEASURED']){const spec=motorDraft();spec.physicsInputs.motorTorqueNm=input(.44*.0980665,basis);spec.physicsInputs.motorStallTorqueNm=input(1,'ASSUMED');assert.match(generationCatalogIssues(spec,motorCatalog).join('\n'),/at or above.*published stall torque/);}assert.match(generationCatalogIssues({physicsInputs:{motorTorqueNm:input(.1),motorStallTorqueNm:input(.1)}},{components:[]}).join('\n'),/below motorStallTorqueNm/);});
test('generation catalog guard distinguishes missing or unsupported data from actual ratings',()=>{const spec=motorDraft(),catalog=structuredClone(motorCatalog);delete catalog.components[0].ratings.voltageV;catalog.components[0].ratings.noLoadRpm.unit='rad/s';const issues=generationCatalogIssues(spec,catalog);assert.equal(issues.length,2);assert(issues.every(i=>i.includes('no supported published')));assert.deepEqual(generationCatalogIssues({parts:[{shape:{type:'box'}}],physicsInputs:{motorNoLoadRpm:input(270)}},catalog),[]);spec.physicsInputs.motorNoLoadRpm.basis='ASSUMED';assert.equal(generationCatalogIssues(spec,catalog).length,1);});

test('initial catalog preflight rejects metadata-only, missing and malformed native sources without admission or mutation',()=>{
  const spec={parts:[{id:'a',shape:{type:'catalog',catalogId:'metadata-only'}},{id:'b',shape:{type:'catalog',catalogId:'metadata-only'}}]},before=structuredClone(spec);
  for(const geometry of [undefined,null,{}, {step:'',sha256:'a'.repeat(64)},{step:'models/missing.step'},{step:'models/missing.step',sha256:'claimed-verified'},{step:'../../secret.step',sha256:'a'.repeat(64)},{step:'https://host/model.step',sha256:'a'.repeat(64)},{step:'models/model.stl',sha256:'a'.repeat(64)}]){
    const catalog={components:[{id:'metadata-only',geometry}]},snapshot=structuredClone(catalog),issues=generationCatalogIssues(spec,catalog);assert.equal(issues.length,1);assert.match(issues[0],/metadata-only.*no admitted source STEP path and SHA-256/);assert.match(issues[0],/ASSUMED purchased envelope/);assert.deepEqual(catalog,snapshot);assert.deepEqual(spec,before);
  }
  assert.equal(generationCatalogIssues(spec,{components:[]}).length,1,'Candidate or missing IDs cannot become runtime catalog parts');
  assert.deepEqual(generationCatalogIssues(spec,{components:[{id:'metadata-only',geometry:sourceGeometry}]}),[],'This checks metadata, not file existence or native geometry');
  assert.deepEqual(generationCatalogIssues({parts:[{id:'envelope',kind:'purchased',shape:{type:'box',size:[10,10,10]}}]},{components:[]}),[],'Explicit envelopes do not pretend to import source geometry');
});

test('known selected-SKU ratings cannot be bypassed by ASSUMED USER or MEASURED labels',()=>{
  for(const basis of ['ASSUMED','USER','MEASURED'])for(const [key,value] of Object.entries({motorNoLoadRpm:1000,motorStallTorqueNm:.2,motorStallA:9,motorVoltage:24})){
    const spec=motorDraft();spec.physicsInputs[key]=input(value,basis);const before=structuredClone(spec),issues=generationCatalogIssues(spec,motorCatalog);assert.equal(issues.length,1);assert.match(issues[0],new RegExp(key+'.*contradicts selected motor-1098'));assert.deepEqual(spec,before);
  }
  const exact=motorDraft();for(const value of Object.values(exact.physicsInputs))value.basis='ASSUMED';const before=structuredClone(exact);assert.deepEqual(generationCatalogIssues(exact,motorCatalog),[]);assert.deepEqual(exact,before,'Consistency does not promote an ASSUMED input to manufacturer evidence');
  const missing=structuredClone(motorCatalog);delete missing.components[0].ratings.noLoadRpm;exact.physicsInputs.motorNoLoadRpm=input(1000,'ASSUMED');assert.deepEqual(generationCatalogIssues(exact,missing),[],'No known published mapping means no invented reference number');exact.physicsInputs.motorNoLoadRpm.basis='MANUFACTURER';assert.match(generationCatalogIssues(exact,missing).join('\n'),/no supported published noLoadRpm/);
});
