import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,readdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createProjectStore} from '../server/studio-projects.mjs';
import {designHash} from '../server/studio-contract.mjs';
const sample=()=>({schemaVersion:1,title:'Block',description:'A test part',units:'mm',requirements:[{id:'r1',text:'A block'}],assumptions:[],unknowns:[],questions:[],parts:[{id:'block',name:'Block',kind:'printed',material:'PLA',color:'#123456',shape:{type:'box',size:[20,20,5]},position:[0,0,0],rotation:[0,0,0]}],assembly:[{id:'inspect',title:'Inspect',partIds:['block'],requires:[],instructions:['Inspect.'],checks:['Measure.']}]});
async function fixture(execute=async(p,i,save)=>save({workflow:{status:'complete',stage:'complete'}}),findJob){const root=await mkdtemp(path.join(tmpdir(),'m4ke-project-test-'));return {root,store:createProjectStore({root,execute,findJob}),close:()=>rm(root,{recursive:true,force:true})};}
async function settled(store,id){for(let i=0;i<200;i++){const p=await store.get(id);if(p.workflow?.status!=='running'&&!store.isRunning())return p;await new Promise(r=>setTimeout(r,5));}throw new Error('Fixture workflow timed out');}
test('DGX project persists normalized spec with revisions and rejects stale overwrites',async()=>{const f=await fixture();try{const p=await f.store.create({request:'make block',spec:sample()});assert.equal(p.revision,1);assert.equal(p.designHash,designHash(sample()));const next=await f.store.update(p.id,{expectedRevision:1,request:'make two blocks',jobId:null});assert.equal(next.revision,2);assert.equal(next.jobId,null);await assert.rejects(f.store.update(p.id,{expectedRevision:1,request:'lost update'}),e=>e.status===409);const disk=JSON.parse(await readFile(path.join(f.root,'data','studio-projects',p.id+'.json'),'utf8'));assert.equal(disk.request,'make two blocks');}finally{await f.close();}});
test('concurrent optimistic saves cannot overwrite each other',async()=>{const f=await fixture();try{const p=await f.store.create({request:'toy'});const result=await Promise.allSettled(['one','two'].map(request=>f.store.update(p.id,{expectedRevision:1,request})));assert.equal(result.filter(x=>x.status==='fulfilled').length,1);assert.equal(result.find(x=>x.status==='rejected').reason.status,409);}finally{await f.close();}});
test('authoritative project links only matching job revisions',async()=>{const spec=sample();const f=await fixture(undefined,async()=>({designHash:designHash(spec)}));try{const p=await f.store.create({request:'toy',spec});const jobId='12345678-1234-4234-8234-123456789abc';assert.equal((await f.store.update(p.id,{expectedRevision:1,jobId})).jobId,jobId);const edited=sample();edited.parts[0].shape.size[0]=30;await assert.rejects(f.store.update(p.id,{expectedRevision:2,spec:edited,jobId}),/does not match/);}finally{await f.close();}});
test('automatic workflow survives browser disconnect, blocks edits, and retains attempts',async()=>{let release;const gate=new Promise(r=>release=r);const f=await fixture(async(p,i,save)=>{await gate;await save({workflow:{stage:'verify',attempts:[{number:1,status:'complete',criticalFailures:[]}]}});await save({workflow:{status:'complete',stage:'complete'}});});try{const p=await f.store.create({request:'toy'});const started=await f.store.start(p.id);assert.equal(started.workflow.status,'running');await assert.rejects(f.store.update(p.id,{expectedRevision:started.revision,request:'new'}),e=>e.status===409);await assert.rejects(f.store.start(p.id),e=>e.status===429);release();const done=await settled(f.store,p.id);assert.equal(done.workflow.status,'complete');assert.equal(done.workflow.attempts.length,1);await f.store.start(p.id);await settled(f.store,p.id);const history=await readdir(path.join(f.root,'data','studio-projects',p.id+'-runs'));assert.equal(history.length,1);}finally{release();await f.close();}});
test('interrupted workflow cannot resurrect a completion claim',async()=>{const f=await fixture();try{const p=await f.store.create({request:'toy'});p.workflow={id:'12345678-1234-4234-8234-123456789abc',status:'running',stage:'cad',attempts:[{number:1,jobId:'diagnostic-job'}]};await writeFile(path.join(f.root,'data','studio-projects',p.id+'.json'),JSON.stringify(p));const reloaded=await f.store.get(p.id);assert.equal(reloaded.workflow.status,'error');assert.match(reloaded.workflow.message,/restarted/);assert.equal(reloaded.workflow.attempts.length,1);}finally{await f.close();}});
test('exceptions are persisted as errors, not hidden behind success',async()=>{const f=await fixture(async()=>{throw new Error('Kernel rejected negative control');});try{const p=await f.store.create({request:'toy'});await f.store.start(p.id);const done=await settled(f.store,p.id);assert.equal(done.workflow.status,'error');assert.match(done.workflow.message,/negative control/);assert.equal(f.store.isRunning(),false);}finally{await f.close();}});
test('questions are a resumable state and untrusted project fields are rejected',async()=>{const f=await fixture(async(p,i,save)=>save({workflow:{status:'questions',stage:'questions'}}));try{const p=await f.store.create({request:'toy'});await f.store.start(p.id);assert.equal((await settled(f.store,p.id)).workflow.status,'questions');await assert.rejects(f.store.create({request:'toy',verification:{overall:'PASS'}}),/Unsupported/);await assert.rejects(f.store.get('../escape'),/Invalid/);await assert.rejects(f.store.start(p.id,{parameters:'shell code'}),/Invalid/);assert.equal(f.store.isRunning(),false);}finally{await f.close();}});
