import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm,rename} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {loadPreviewLibrary,readPreviewAsset} from '../server/studio-previews.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
function glb(json={asset:{version:'2.0'}}){let text=JSON.stringify(json);while(text.length%4)text+=' ';const bytes=Buffer.alloc(20+text.length);bytes.writeUInt32LE(0x46546c67,0);bytes.writeUInt32LE(2,4);bytes.writeUInt32LE(bytes.length,8);bytes.writeUInt32LE(text.length,12);bytes.writeUInt32LE(0x4e4f534a,16);bytes.write(text,20);return bytes;}
async function fixture({uri=false}={}){
  const root=await mkdtemp(path.join(tmpdir(),'m4ke-preview-')),folder=path.join(root,'database/model-library'),preview=path.join(folder,'preview-quality-10');await mkdir(preview,{recursive:true});
  const source=Buffer.from('unit fixture STEP identity, not actual CAD'),sourceSha=sha(source),bytes=glb(uri?{asset:{version:'2.0'},buffers:[{uri:'https://example.invalid/leak'}]}:undefined);
  const index=Buffer.from(JSON.stringify({schema:'m4ke-model-library-candidate-index-2',records:[{sha256:sourceSha,relative_file:'part.step'}]}));await writeFile(path.join(folder,'CANDIDATE-INDEX-20260927-06.json'),index);await writeFile(path.join(folder,'part.step'),source);await writeFile(path.join(preview,'part.glb'),bytes);
  const level={file:'part.glb',sha256:sha(bytes),bytes:bytes.length,triangles:12,source_frame_bounds_mm:[0,0,0,1,2,3],position_index_normal_checks:'PASS'};
  const record={name:'Fixture',source_sha256:sourceSha,source_file:'part.step',source_record:{sha256:sourceSha,license_file:'fixture-only'},status:'PREVIEW_GEOMETRY_CHECKS_PASS',runtime_qualified:false,physical_fit:'UNKNOWN',native:{bounds_mm:[0,0,0,1,2,3],solids:1},levels:{overview:level,detail:level},quality_gates:Object.fromEntries(['all_native_solids_and_faces_retained','all_detail_faces_meshed','detail_bounds_within_0_03_mm','detail_volume_within_1_percent','detail_not_less_dense','each_file_below_32_MiB'].map(key=>[key,true]))};
  const manifest={schema:'m4ke-library-preview-assets-1',source_index:'CANDIDATE-INDEX-20260927-06.json',source_index_sha256:sha(index),coordinate_contract:{auto_centered:false,glb_to_source:'source_mm = [gltf_x,-gltf_z,gltf_y] * 1000'},records:[record]};
  const save=()=>writeFile(path.join(preview,'manifest.json'),JSON.stringify(manifest));await save();return {root,folder,preview,record,manifest,save,sourceSha,bytes,close:()=>rm(root,{recursive:true,force:true})};
}
test('source previews retain qualified preview metadata, not runtime promotion or filesystem paths',async()=>{const f=await fixture();try{const data=await loadPreviewLibrary(f.root);assert.equal(data.available,true);assert.equal(data.records.length,1);assert.equal(data.records[0].buildQualified,false);assert.equal(data.records[0].physicalValidation,'UNKNOWN');assert(!JSON.stringify(data).includes('part.step'));const asset=await readPreviewAsset(f.root,f.sourceSha,'detail');assert.deepEqual(asset.bytes,f.bytes);assert.equal(asset.sourceSha256,f.sourceSha);}finally{await f.close();}});
test('failed preview gates never offer assets',async()=>{const f=await fixture();try{f.record.quality_gates.all_detail_faces_meshed=false;await f.save();assert.equal((await loadPreviewLibrary(f.root)).records.length,0);await assert.rejects(readPreviewAsset(f.root,f.sourceSha,'detail'),e=>e.status===404);}finally{await f.close();}});
test('changed source STEP withholds an otherwise intact preview',async()=>{const f=await fixture();try{await writeFile(path.join(f.folder,'part.step'),'changed source');await assert.rejects(readPreviewAsset(f.root,f.sourceSha,'overview'),/Source STEP changed/);}finally{await f.close();}});
test('changed GLB withholds a preview even with unchanged source',async()=>{const f=await fixture();try{await writeFile(path.join(f.preview,'part.glb'),'changed asset');await assert.rejects(readPreviewAsset(f.root,f.sourceSha,'detail'),/Preview bytes changed/);}finally{await f.close();}});
test('source index and coordinate contract changes cannot silently rescale or substitute',async()=>{const f=await fixture();try{f.manifest.coordinate_contract.auto_centered=true;await f.save();assert.equal((await loadPreviewLibrary(f.root)).available,false);f.manifest.coordinate_contract.auto_centered=false;await f.save();await writeFile(path.join(f.folder,'CANDIDATE-INDEX-20260927-06.json'),'{}');assert.equal((await loadPreviewLibrary(f.root)).available,false);}finally{await f.close();}});
test('external glTF resources are rejected before browser loading',async()=>{const f=await fixture({uri:true});try{await assert.rejects(readPreviewAsset(f.root,f.sourceSha,'detail'),/URI resources/);}finally{await f.close();}});
test('invalid identities, paths and oversized declared meshes are rejected',async()=>{const f=await fixture();try{await assert.rejects(readPreviewAsset(f.root,'../secret','detail'),e=>e.status===400);await assert.rejects(readPreviewAsset(f.root,f.sourceSha,'../secret'),e=>e.status===400);f.record.levels.detail.file='../secret.glb';await f.save();assert.equal((await loadPreviewLibrary(f.root)).records.length,0);f.record.levels.detail.file='part.glb';f.record.levels.detail.bytes=33*1024*1024;await f.save();assert.equal((await loadPreviewLibrary(f.root)).records.length,0);}finally{await f.close();}});
test('invalid solid-count metadata cannot reach React as an object',async()=>{const f=await fixture();try{f.record.native.solids={unexpected:'object'};await f.save();assert.equal((await loadPreviewLibrary(f.root)).records.length,0);}finally{await f.close();}});
test('only two bounded asset reads are admitted concurrently and slots release afterward',async()=>{const f=await fixture();try{const first=readPreviewAsset(f.root,f.sourceSha,'overview'),second=readPreviewAsset(f.root,f.sourceSha,'detail');await assert.rejects(readPreviewAsset(f.root,f.sourceSha,'detail'),e=>e.status===429);await Promise.all([first,second]);assert.equal((await readPreviewAsset(f.root,f.sourceSha,'detail')).bytes.length,f.bytes.length);}finally{await f.close();}});
test('preview10 selection never falls back to an old preview09 installation',async()=>{const f=await fixture();try{assert.equal((await loadPreviewLibrary(f.root)).manifestFile,'preview-quality-10/manifest.json');await rename(f.preview,path.join(f.folder,'preview-quality-09'));const data=await loadPreviewLibrary(f.root);assert.equal(data.available,false);assert.deepEqual(data.records,[]);}finally{await f.close();}});
