export type Parameters = {width:number;wheelRadius:number;rpm:number;angle:number;clearance:number;thickness:number};
export type ParameterKey = keyof Parameters;
export const LIMITS:Record<ParameterKey,[number,number]>={width:[180,340],wheelRadius:[35,75],rpm:[300,3000],angle:[15,70],clearance:[0,10],thickness:[2,12]};
export const DEFAULTS:Parameters={width:280,wheelRadius:45,rpm:900,angle:42,clearance:1.8,thickness:4};
export const PARAM_META:Record<ParameterKey,{label:string;unit:string;step:number}>={width:{label:'Chassis width',unit:'mm',step:1},wheelRadius:{label:'Flywheel radius',unit:'mm',step:1},rpm:{label:'Flywheel speed',unit:'rpm',step:50},angle:{label:'Launch angle',unit:'°',step:1},clearance:{label:'Motor clearance',unit:'mm',step:.1},thickness:{label:'Mount thickness',unit:'mm',step:.5}};
export function validateParameters(value:unknown):value is Parameters {if(!value||typeof value!=='object')return false;return Object.entries(LIMITS).every(([k,[lo,hi]])=>{const n=(value as Record<string,unknown>)[k];return typeof n==='number'&&Number.isFinite(n)&&n>=lo&&n<=hi;});}
export function signature(p:Parameters){return (Object.keys(LIMITS) as ParameterKey[]).map(k=>`${k}:${p[k]}`).join('|');}
export type Part={id:string;name:string;group:string;material:string;qty:number;method:string;description:string};
export const PARTS:Part[]=[
 {id:'chassis',name:'Base chassis',group:'Structure',material:'Aluminium concept',qty:1,method:'Cut / drill',description:'The datum for the assembly. Establish a flat, stable base before installing moving parts.'},
 {id:'frame',name:'Side frames',group:'Structure',material:'PETG concept',qty:2,method:'FDM concept',description:'Paired structural supports locate the wheel assembly. Stiffness is not yet validated.'},
 {id:'wheel-left',name:'Flywheel · left',group:'Launcher',material:'Polymer + elastomer',qty:1,method:'Purchased / custom',description:'Left drive wheel. Radius changes alter surface velocity, packaging and stored energy.'},
 {id:'wheel-right',name:'Flywheel · right',group:'Launcher',material:'Polymer + elastomer',qty:1,method:'Purchased / custom',description:'Counter-rotating right wheel. Grip, balance and ball compression require testing.'},
 {id:'shaft',name:'Drive shafts',group:'Launcher',material:'Steel concept',qty:2,method:'Purchased',description:'Concentric shafts connect the wheel hubs to the drive system. Bearing fit remains unverified.'},
 {id:'motor',name:'Drive motors',group:'Drive',material:'Purchased component',qty:2,method:'Supplier selection',description:'Representative motor envelopes, not a selected motor SKU. Torque and current data are missing.'},
 {id:'motor-mount',name:'Motor mount',group:'Drive',material:'PETG concept',qty:2,method:'FDM concept',description:'Parametric mounting plate. Blue highlighting links this part to its clearances and assembly step.'},
 {id:'feed',name:'Ball guide',group:'Launcher',material:'PETG concept',qty:1,method:'FDM concept',description:'A concept guide for a 60 mm demonstration ball. Not a full-size basketball launcher.'},
 {id:'electronics',name:'Control enclosure',group:'Electronics',material:'ABS concept',qty:1,method:'Purchased enclosure',description:'Placeholder electronics enclosure. Wiring, interlock and emergency stop are not yet engineered.'},
];
export type Check={id:string;name:string;group:string;status:'PASS'|'FAIL'|'UNKNOWN';actual:string;required:string;method:string;detail:string;partIds:string[];margin?:string};
export const METHOD_VERSION='m4ke-analytical-v1';
export type Evidence={methodVersion?:string;version:number;signature:string;createdAt:string;checks:Check[]};
export function calculate(p:Parameters,version:number):Evidence{
 if(!validateParameters(p))throw new Error('Parameters are outside supported limits');
 const surface=2*Math.PI*(p.wheelRadius/1000)*p.rpm/60;
 const speed=surface*.7;const range=speed*speed*Math.sin(2*p.angle*Math.PI/180)/9.81;
 const envelope=4*p.wheelRadius+80;
 return {methodVersion:METHOD_VERSION,version,signature:signature(p),createdAt:new Date().toISOString(),checks:[
 {id:'trajectory',name:'Ideal trajectory',group:'Performance',status:range>=2.5?'PASS':'FAIL',actual:`${range.toFixed(2)} m`,required:'≥ 2.50 m · same-height target',margin:`${(range-2.5)>=0?'+':''}${(range-2.5).toFixed(2)} m`,method:'Analytical estimate',detail:`R = v² sin(2θ) / g. Assumes 70% wheel-to-ball speed transfer, no drag and equal launch/landing height. These assumptions are not measured. Calculated range is not a successful shot.`,partIds:['wheel-left','wheel-right','feed']},
 {id:'velocity',name:'Estimated exit speed',group:'Performance',status:'UNKNOWN',actual:`${speed.toFixed(2)} m/s`,required:'Measured transfer efficiency',method:'Assumption-based estimate',detail:`v = 0.70 × 2πr × RPM/60. Wheel surface speed ${surface.toFixed(2)} m/s. Ball slip, deformation and motor droop are unmeasured.`,partIds:['wheel-left','wheel-right','motor']},
 {id:'clearance',name:'Motor clearance',group:'Mechanical',status:p.clearance>=1.5?'PASS':'FAIL',actual:`${p.clearance.toFixed(1)} mm`,required:'≥ 1.5 mm nominal',margin:`${p.clearance>=1.5?'+':''}${(p.clearance-1.5).toFixed(1)} mm`,method:'Parametric nominal gap',detail:'The rendered spacer gap equals this parameter. This checks one nominal spacing, not a general collision sweep. Print tolerance, flex and installation variation are excluded.',partIds:['motor','motor-mount','frame']},
 {id:'packaging',name:'Wheel packaging',group:'Mechanical',status:p.width>=envelope?'PASS':'FAIL',actual:`${p.width.toFixed(0)} mm available`,required:`≥ ${envelope.toFixed(0)} mm`,margin:`${p.width-envelope>=0?'+':''}${(p.width-envelope).toFixed(0)} mm`,method:'Envelope inequality',detail:'Required width = four wheel radii + 56 mm gap + 24 mm frame allowance. Demonstration ball diameter 60 mm, nominal compression 4 mm. This is packaging only, not a grip model.',partIds:['wheel-left','wheel-right','frame','chassis']},
 {id:'volume',name:'Build envelope',group:'Manufacturing',status:p.width<=300?'PASS':'FAIL',actual:`${p.width} × 260 × 270 mm`,required:'≤ 300 × 300 × 300 mm',method:'Concept bounding dimensions',detail:'Concept assembled envelope compared with a 300 mm cube. Does not guarantee that each exported piece is printable, oriented correctly or supported.',partIds:['chassis','frame']},
 {id:'torque',name:'Motor torque',group:'Mechanical',status:'UNKNOWN',actual:'No motor data',required:'Torque curve + load model',method:'Missing evidence',detail:'No selected motor SKU, duty cycle, inertia, shaft stress or bearing load calculation. A language model cannot turn missing supplier/test data into verification.',partIds:['motor','shaft']},
 {id:'print',name:'Printability & strength',group:'Manufacturing',status:'UNKNOWN',actual:'Not tested',required:'Printer profile + material test',method:'Missing physical validation',detail:'No slicer validation, anisotropic strength data, fastener retention or fatigue test. Mesh export is a concept, not a manufacturing release.',partIds:['motor-mount','frame','feed']},
 {id:'safety',name:'Guarding & interlocks',group:'Safety',status:'UNKNOWN',actual:'Operation blocked',required:'Independent safety review',method:'Missing safety validation',detail:'Exposed rotating parts, stored energy and projectile risk remain. Instructions are an unpowered concept walkthrough; do not energize or manufacture for operation from this demo.',partIds:['wheel-left','wheel-right','electronics']}
 ]};
}
export type Step={id:string;title:string;partIds:string[];tools:string[];actions:string[];checklist:string[];why:string;warning:string;dependsOn:string[]};
export const STEPS:Step[]=[
 {id:'prepare',title:'Prepare the workspace',partIds:['chassis'],tools:['Parts checklist','Flat work surface'],actions:['Review the concept bill of materials.','Keep all power sources disconnected.','Inspect representative parts for damage and sharp edges.'],checklist:['Power disconnected','Parts inventoried'],why:'Assembly starts with a stable, unpowered workspace—not a green badge.',warning:'Illustrative assembly plan. Hardware sizes and physical fit are not validated.',dependsOn:[]},
 {id:'base',title:'Establish the base',partIds:['chassis'],tools:['Straightedge','Square'],actions:['Place the base on a flat surface.','Identify the forward launch direction.','Check the base sits without rocking.'],checklist:['Base stable','Direction identified'],why:'Every later alignment depends on this datum.',warning:'A rendered flat base does not prove the physical part is flat.',dependsOn:['prepare']},
 {id:'frame-step',title:'Position the side frames',partIds:['frame','chassis'],tools:['Square','Clamps'],actions:['Position paired supports symmetrically.','Check the wheel envelope fits between the supports.','Use temporary retention until the fit is reviewed.'],checklist:['Supports aligned','Wheel envelope reviewed'],why:'Alignment errors propagate to bearings, shafts and wheel contact.',warning:'Fastener selection and tightening torque must come from the final engineering design.',dependsOn:['base']},
 {id:'mount-step',title:'Fit the motor mounts',partIds:['motor-mount','frame'],tools:['Caliper','Appropriate driver'],actions:['Locate the mounting faces shown in blue.','Check mount thickness against the current revision.','Measure the nominal spacer gap before retaining the plates.'],checklist:['Mount faces seated','Gap checked'],why:'A visible, measurable interface makes assembly errors easier to catch.',warning:'The 1.5 mm threshold is a demo design requirement, not a validated universal clearance.',dependsOn:['frame-step']},
 {id:'motor-step',title:'Install the drive motors',partIds:['motor','motor-mount'],tools:['Supplier-specified driver','Caliper'],actions:['Use the selected motor supplier’s mounting instructions.','Align each motor with its mount without power.','Verify no contact with the adjacent frame.'],checklist:['Supplier instructions reviewed','No nominal frame contact'],why:'Mounting alignment helps avoid side loads and vibration.',warning:'Motor models shown are envelopes only. No real SKU or approved fastener torque is specified.',dependsOn:['mount-step']},
 {id:'shaft-step',title:'Check shaft alignment',partIds:['shaft','motor'],tools:['Straightedge','Supplier fit gauges'],actions:['Review the shaft and coupling interfaces.','Confirm bearings and retention are specified in the final design.','Check concentric alignment before fitting wheels.'],checklist:['Interfaces reviewed','Retention specified'],why:'A visually aligned shaft is not evidence of safe retention at speed.',warning:'Do not operate without an independently checked shaft, bearing and retention design.',dependsOn:['motor-step']},
 {id:'wheels-step',title:'Position the flywheels',partIds:['wheel-left','wheel-right','shaft'],tools:['Caliper','Balance/retention specification'],actions:['Position the two representative wheels.','Review the nominal 56 mm surface gap for the 60 mm demo ball.','Record that balance, friction and retention remain untested.'],checklist:['Wheel spacing reviewed','Untested assumptions recorded'],why:'Wheel geometry connects the product requirement to the velocity estimate.',warning:'Exposed wheels are a pinch and ejection hazard. Keep power disconnected.',dependsOn:['shaft-step']},
 {id:'feed-step',title:'Align the ball guide',partIds:['feed','frame'],tools:['Square','Caliper'],actions:['Align the guide with the launch plane.','Compare its orientation to the launch-angle parameter.','Inspect for potential ball snags by hand, with power disconnected.'],checklist:['Guide aligned','Unpowered path inspected'],why:'A guide that changes the release angle invalidates the trajectory estimate.',warning:'Shown geometry is conceptual, not a proven feeder mechanism.',dependsOn:['wheels-step']},
 {id:'control-step',title:'Review the control enclosure',partIds:['electronics','chassis'],tools:['Circuit review checklist'],actions:['Locate the representative enclosure.','Record missing wiring, guarding and emergency-stop designs.','Do not connect a power source.'],checklist:['Missing safety items recorded','Power remains disconnected'],why:'The absence of a safety design must stay visible through the build.',warning:'No wiring or energization instructions are supplied by this prototype.',dependsOn:['feed-step']},
 {id:'review-step',title:'Complete the unpowered review',partIds:['chassis','wheel-left','wheel-right','motor'],tools:['Evidence report','Independent reviewer'],actions:['Re-run checks for the current design version.','Read all FAIL and UNKNOWN items.','Export the concept packet for independent engineering review.'],checklist:['Current evidence reviewed','No operation claimed'],why:'Finishing a checklist is not the same as validating a machine.',warning:'STOP: powered testing is outside this assembly guide. Independent engineering and safety validation required.',dependsOn:['control-step']}
];
export type Revision={version:number;parameters:Parameters;label:string;createdAt:string};
export type Project={schemaVersion:1;name:string;version:number;parameters:Parameters;history:Revision[];evidence:Evidence|null;completed:string[]};
export function newProject():Project{return {schemaVersion:1,name:'Basketball shooting robot',version:1,parameters:{...DEFAULTS},history:[{version:1,parameters:{...DEFAULTS},label:'Initial concept',createdAt:new Date().toISOString()}],evidence:null,completed:[]};}
export function applyChanges(project:Project,changes:Partial<Parameters>,label:string):Project {for(const key of Object.keys(changes))if(!Object.hasOwn(LIMITS,key))throw new Error('Unsupported parameter'); const parameters={...project.parameters,...changes};if(!validateParameters(parameters))throw new Error('Parameter outside supported range');if(signature(parameters)===signature(project.parameters))return project;const version=project.version+1;return {...project,version,parameters,completed:[],history:[...project.history,{version,parameters,label,createdAt:new Date().toISOString()}].slice(-30)};}
export function evidenceCurrent(project:Project){return !!project.evidence&&project.evidence.version===project.version&&project.evidence.signature===signature(project.parameters);}
export function canComplete(step:Step,completed:string[]){return step.dependsOn.every(id=>completed.includes(id));}
export function completionBlockReason(project:Project,step:Step):string|null {
 if(!canComplete(step,project.completed))return 'Complete the previous step before confirming this one.';
 if(step.id==='review-step'&&!evidenceCurrent(project))return 'Run checks for this revision before completing the final review.';
 return null;
}
export function completeStep(project:Project,id:string,checked:string[]):Project {
 const step=STEPS.find(s=>s.id===id);if(!step)throw new Error('Unknown assembly step');
 const blocked=completionBlockReason(project,step);if(blocked)throw new Error(blocked);
 if(!step.checklist.every(item=>checked.includes(item)))throw new Error('Review every checklist item first');
 return {...project,completed:[...new Set([...project.completed,id])]};
}
export function reopenStep(project:Project,id:string):Project {
 if(!STEPS.some(s=>s.id===id))throw new Error('Unknown assembly step');
 const reset=new Set([id]);let changed=true;
 while(changed){changed=false;for(const step of STEPS)if(!reset.has(step.id)&&step.dependsOn.some(parent=>reset.has(parent))){reset.add(step.id);changed=true;}}
 return {...project,completed:project.completed.filter(stepId=>!reset.has(stepId))};
}
export function loadProject(raw:string):Project {const p=JSON.parse(raw);if(!p||p.schemaVersion!==1||!validateParameters(p.parameters)||!Number.isSafeInteger(p.version)||p.version<1||!Array.isArray(p.history)||typeof p.name!=='string'||p.name.length>120)throw new Error('Unsupported or invalid project file');const clean=newProject();const pick=(v:Parameters)=>Object.fromEntries((Object.keys(LIMITS) as ParameterKey[]).map(k=>[k,v[k]])) as Parameters;return {...clean,name:p.name,version:p.version,parameters:pick(p.parameters),history:p.history.filter((r:Revision)=>r&&Number.isSafeInteger(r.version)&&r.version>0&&r.version<=p.version&&validateParameters(r.parameters)&&typeof r.label==='string'&&r.label.length<=200&&typeof r.createdAt==='string'&&Number.isFinite(Date.parse(r.createdAt))).slice(-30).map((r:Revision)=>({version:r.version,parameters:pick(r.parameters),label:r.label,createdAt:r.createdAt})),completed:[],evidence:null};}
export function restoreLocal(raw:string):Project {
 const p=JSON.parse(raw);const clean=loadProject(raw);
 // Recompute from known revision inputs, never trust stored PASS values.
 // Retain the original timestamp only for the same calculation method.
 if(p.evidence&&Number.isInteger(p.evidence.version)){
  const revision=p.evidence.version===clean.version?{parameters:clean.parameters}:clean.history.find(r=>r.version===p.evidence.version);
  if(revision&&p.evidence.signature===signature(revision.parameters)){
   clean.evidence=calculate(revision.parameters,p.evidence.version);
   if(p.evidence.methodVersion===METHOD_VERSION&&typeof p.evidence.createdAt==='string'&&Number.isFinite(Date.parse(p.evidence.createdAt)))clean.evidence.createdAt=p.evidence.createdAt;
  }
 }
 if(Array.isArray(p.completed))for(const step of STEPS)if(p.completed.includes(step.id)&&!completionBlockReason(clean,step))clean.completed.push(step.id);
 return clean;
}
export function csvBOM(){return ['Part ID,Part,Quantity,Material,Method,Status',...PARTS.map(p=>[p.id,p.name,p.qty,p.material,p.method,'CONCEPT - NOT RELEASED'].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\r\n');}
export function mountDXF(p:Parameters){const w=80,h=45;const rows=['0','SECTION','2','HEADER','9','$INSUNITS','70','4','0','ENDSEC','0','SECTION','2','ENTITIES'];for(const [x1,y1,x2,y2] of [[0,0,w,0],[w,0,w,h],[w,h,0,h],[0,h,0,0]])rows.push('0','LINE','8','CONCEPT','10',String(x1),'20',String(y1),'30','0','11',String(x2),'21',String(y2),'31','0');for(const [x,y] of [[8,8],[72,8],[8,37],[72,37]])rows.push('0','CIRCLE','8','HOLES','10',String(x),'20',String(y),'30','0','40','1.6');rows.push('0','TEXT','8','NOTES','10','0','20','-8','30','0','40','2.5','1',`CONCEPT ONLY - thickness ${p.thickness} mm - confirm motor hole pattern`,'0','ENDSEC','0','EOF');return rows.join('\n');}
